import marimo

__generated_with = "0.18.4"
app = marimo.App(width="full")


@app.cell
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def _(mo, pyoso_db_conn):
    def get_model_preview(model_name, limit=5):
        return mo.sql(f"SELECT * FROM {model_name} LIMIT {limit}", 
                      engine=pyoso_db_conn, output=False)

    def get_row_count(model_name):
        result = mo.sql(f"SHOW STATS FOR {model_name}", 
                        engine=pyoso_db_conn, output=False)
        return result['row_count'].sum()    

    def generate_sql_snippet(model_name, df_results, limit=5):
        column_names = df_results.columns.tolist()
        # Format columns with one per line, indented
        columns_formatted = ',\n  '.join(column_names)
        sql_snippet = f"""```sql
SELECT 
  {columns_formatted}
FROM {model_name}
LIMIT {limit}
```
"""
        return mo.md(sql_snippet)

    def render_table_accordion(model_names):
        accordion = {}
        for model_name in model_names:
            df = get_model_preview(model_name)
            sql_snippet = generate_sql_snippet(model_name, df, limit=5)
            fmt = {c: '{:.0f}' for c in df.columns if df[c].dtype == 'int64' and ('_id' in c or c == 'id')}
            table = mo.ui.table(df, format_mapping=fmt, show_column_summaries=False, show_data_types=False)
            row_count = get_row_count(model_name)
            col_count = len(df.columns)
            title = f"{model_name} | {row_count:,.0f} rows, {col_count} cols"
            accordion[title] = mo.vstack([sql_snippet, table])
        return mo.accordion(accordion)
    return (render_table_accordion,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        # Open Dev Data

        Open Dev Data provides comprehensive developer activity metrics, ecosystem 
        mappings, and contribution analytics across crypto/web3 ecosystems.

        **Maintained by:** [Electric Capital](https://electriccapital.com)
        """
    )
    return


@app.cell(hide_code=True)
def _(render_table_accordion):
    render_table_accordion([
        "stg_opendevdata__canonical_developer_locations",
        "stg_opendevdata__canonical_developers",
        "stg_opendevdata__commits",
        "stg_opendevdata__developer_activities",
        "stg_opendevdata__eco_developer_28d_activities",
        "stg_opendevdata__eco_developer_activities",
        "stg_opendevdata__eco_developer_contribution_ranks",
        "stg_opendevdata__eco_developer_tenures",
        "stg_opendevdata__eco_mads",
        "stg_opendevdata__ecosystems_child_ecosystems_recursive",
        "stg_opendevdata__ecosystems_child_ecosystems",
        "stg_opendevdata__ecosystems_organizations",
        "stg_opendevdata__ecosystems_repos_recursive",
        "stg_opendevdata__ecosystems_repos",
        "stg_opendevdata__ecosystems",
        "stg_opendevdata__organizations",
        "stg_opendevdata__repo_developer_28d_activities",
        "stg_opendevdata__repo_developer_activities",
        "stg_opendevdata__repos"
    ])
    return


if __name__ == "__main__":
    app.run()
