import marimo

__generated_with = "unknown"
app = marimo.App()


@app.cell
def _(mo, pyoso_db_conn):
    df_funding = mo.sql(
        f"""
        SELECT
          funding_date,
          grant_pool_name AS octant_epoch,    
          JSON_EXTRACT_SCALAR(metadata, '$.application_name') AS application,
          to_project_name AS oso_project_name,    
          JSON_EXTRACT_SCALAR(metadata, '$.token_amount') AS amount_eth,
          amount AS amount_usd
        FROM stg_ossd__current_funding
        WHERE from_funder_name = 'octant-golemfoundation'
        """,
        engine=pyoso_db_conn
    )
    return


@app.cell
def _(mo, pyoso_db_conn):
    df_repos = mo.sql(
        f"""
        WITH projects AS (
          SELECT DISTINCT to_project_name AS project_name
          FROM stg_ossd__current_funding
          WHERE from_funder_name = 'octant-golemfoundation'
        ),
        repos AS (
          SELECT DISTINCT
            project_name,
            CONCAT(artifact_namespace, '/', artifact_name) AS repo_name
          FROM artifacts_by_project_v1
          JOIN projects USING project_name
          WHERE artifact_source = 'GITHUB'
        ),
        repo_ids AS (
          SELECT DISTINCT
            project_name,
            repo_id
          FROM int_gharchive__repositories
          JOIN repos USING repo_name
        )
        SELECT DISTINCT
          project_name,
          repo_name,
          repo_created_at,
          star_count,
          fork_count,
          is_opendevdata_blacklist,    
          repo_id,
          opendevdata_id
        FROM int_opendevdata__repositories_with_repo_id
        JOIN repo_ids USING repo_id
        ORDER BY project_name, star_count DESC
        """,
        engine=pyoso_db_conn
    )
    return (df_repos,)


@app.cell
def _(df_repos, mo, pyoso_db_conn, stringify):
    df_contributors = mo.sql(
        f"""
        SELECT
          day,
          repo_id,
          COUNT(DISTINCT IF(l28_days>=10,canonical_developer_id,NULL)) AS full_time_devs,
          COUNT(DISTINCT IF(l28_days<10,canonical_developer_id,NULL)) AS part_time_devs
        FROM stg_opendevdata__repo_developer_28d_activities
        WHERE CAST(repo_id AS VARCHAR) IN ({stringify(df_repos['opendevdata_id'].unique())})
        GROUP BY 1,2
        ORDER BY 1,2
        """,
        engine=pyoso_db_conn
    )
    return


@app.cell
def _():
    stringify = lambda arr: "'" + "','".join([str(x) for x in arr]) + "'"
    return (stringify,)


@app.cell
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


if __name__ == "__main__":
    app.run()
