import marimo

__generated_with = "0.18.4"
app = marimo.App(width="full")


@app.cell
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def _(mo, pyoso_db_conn):
    def get_model_preview(model_name, limit=5):
        return mo.sql(f"SELECT * FROM {model_name} LIMIT {limit}", 
                      engine=pyoso_db_conn, output=False)

    def get_row_count(model_name):
        result = mo.sql(f"SHOW STATS FOR {model_name}", 
                        engine=pyoso_db_conn, output=False)
        return result['row_count'].sum()    
    
    def generate_sql_snippet(model_name, df_results, limit=5):
        column_names = df_results.columns.tolist()
        # Format columns with one per line, indented
        columns_formatted = ',\n  '.join(column_names)
        sql_snippet = f"""```sql
SELECT 
  {columns_formatted}
FROM {model_name}
LIMIT {limit}
```
"""
        return mo.md(sql_snippet)

    def render_table_preview(model_name):
        df = get_model_preview(model_name)
        if df.empty:
            return mo.md(f"**{model_name}**\n\nUnable to retrieve preview (table might be empty or inaccessible).")

        sql_snippet = generate_sql_snippet(model_name, df, limit=5)
        fmt = {c: '{:.0f}' for c in df.columns if df[c].dtype == 'int64' and ('_id' in c or c == 'id')}
        table = mo.ui.table(df, format_mapping=fmt, show_column_summaries=False, show_data_types=False)
        row_count = get_row_count(model_name)
        col_count = len(df.columns)
        title = f"{model_name} | {row_count:,.0f} rows, {col_count} cols"
        return mo.accordion({title: mo.vstack([sql_snippet, table])})
    
    import pandas as pd
    
    def get_format_mapping(df, include_percentage=False):
        """Generate format mapping for table display"""
        fmt = {}
        for c in df.columns:
            if df[c].dtype in ['int64', 'float64']:
                if include_percentage and 'percentage' in c.lower():
                    fmt[c] = '{:.2f}'
                elif '_id' in c or c == 'id' or 'count' in c.lower():
                    fmt[c] = '{:.0f}'
                elif include_percentage:
                    fmt[c] = '{:.0f}'
        return fmt
    
    return (render_table_preview, pd, get_format_mapping)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
        # Commits Model

        This notebook documents the two primary sources of commit data in the OSO platform:
        
        1.  **GitHub Archive Commits**: Commits derived from real-time GitHub events.
        2.  **Open Dev Data Commits**: Commits ingested directly from Git history with identity resolution.
        """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
        ## 1. GitHub Archive Commits

        **Models**: 
        *   `oso.stg_github__commits`
        *   `oso.stg_github__commits_since_20251007`

        These models contain commit data derived from `PushEvent` types in the GitHub Archive stream.

        ### Key Fields
        *   **`push_id`**: The ID of the push event.
        *   **`sha`**: The commit SHA.
        *   **`author_name`** / **`author_email`**: Author information from the commit payload.
        *   **`repository_id`**: GitHub repository ID.
        *   **`created_at`**: Timestamp of the push event.

        ### ⚠️ Data Split (Oct 2025 API Update)
        
        Due to changes in the GitHub Events API payload on **October 7, 2025**, commit data is split into two tables.
        
        *   **`stg_github__commits`**: For events prior to the change.
        *   **`stg_github__commits_since_20251007`**: For events after the change.
        
        Consumers should be aware of this split when querying across this date boundary.
        """
    )
    return


@app.cell(hide_code=True)
def _(render_table_preview):
    render_table_preview("oso.stg_github__commits")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
        ## 2. Open Dev Data Commits

        **Model**: `oso.stg_opendevdata__commits`

        This model represents a curated view of commits obtained by directly analyzing the Git history of repositories. 
        Unlike GitHub Archive events, which are ephemeral, this dataset provides a comprehensive history and includes 
        identity resolution.

        ### Key Fields
        *   **`sha1`**: The full commit hash.
        *   **`repo_id`**: The Open Dev Data repository ID.
        *   **`canonical_developer_id`**: The resolved identity of the developer, linking multiple email addresses or names to a single entity.
        *   **`additions`** / **`deletions`**: Metrics on code churn.
        *   **`committed_at`**: The timestamp when the commit was created.

        This dataset is preferred for analysis requiring precise code churn metrics or developer identity tracking over time.
        """
    )
    return


@app.cell(hide_code=True)
def _(render_table_preview):
    render_table_preview("oso.stg_opendevdata__commits")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
        ## 3. Open Dev Data Commits (Enriched)

        **Model**: `oso.int_opendevdata__commits_with_repo_id`

        This model enriches the raw Open Dev Data commits with the canonical `repo_id`. This allows you to easily join commit data with other datasets that use the unified repository identifier, such as GitHub Archive events.

        ### Key Fields
        *   **`repo_id`**: The canonical repository ID (matches OSS Directory / GitHub Archive).
        *   **`opendevdata_repo_id`**: The original Open Dev Data repository ID.
        *   **`sha1`**: The full commit hash.
        *   **`canonical_developer_id`**: The resolved identity of the developer.
        *   **`github_repository_id`**: The GitHub repository ID (if matched).
        """
    )
    return


@app.cell(hide_code=True)
def _(render_table_preview):
    render_table_preview("oso.int_opendevdata__commits_with_repo_id")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
        ### Example: Join with GitHub Archive Repositories

        Using the enriched commit model to filter commits by repository name from GitHub Archive.
        """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ```sql
        SELECT
            c.commit_author_name,
            COUNT(*) as commit_count
        FROM oso.int_opendevdata__commits_with_repo_id c
        JOIN oso.int_gharchive__repositories r
            ON c.repo_id = r.repo_id
        WHERE r.repo_name = 'opensource-observer/oso'
        GROUP BY c.commit_author_name
        ORDER BY commit_count DESC
        LIMIT 10
        ```
        """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
        ## Sample Queries

        ### Top Contributors (Open Dev Data)
        
        Identify top contributors by commit count for a specific repository using resolved identities.
        """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ```sql
        SELECT
            canonical_developer_id,
            commit_author_name,
            COUNT(*) as commit_count,
            SUM(additions) as total_additions
        FROM oso.stg_opendevdata__commits
        WHERE repo_id = 12345 -- Replace with actual Repo ID
        GROUP BY canonical_developer_id, commit_author_name
        ORDER BY commit_count DESC
        LIMIT 10
        ```
        """
    )
    return


if __name__ == "__main__":
    app.run()
