import marimo

__generated_with = "0.18.4"
app = marimo.App(width="full")


@app.cell
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        # Repositories Model

        The Repositories model combines repository data from multiple sources to create a unified 
        view with consistent `repo_id` identifiers. This notebook explains how we join disparate 
        repository datasets and how different ID systems work together.
        """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ## Data Lineage

        The `int_opendevdata__repositories_with_repo_id` model follows a two-step matching strategy:

        1. **Primary Match (OSSD via GitHub GraphQL ID)**: Open Dev Data repositories are first 
           matched to OSS Directory repositories using `github_graphql_id` → `node_id`. This provides 
           the most reliable `repo_id` mapping.

        2. **Fallback Match (GitHub Archive via Repo Name)**: Repositories that don't match via 
           GraphQL ID are matched by `repo_name` to GitHub Archive repositories, which tracks 
           repository name changes over time.

        3. **Unmatched**: Repositories that don't match either source retain their Open Dev Data 
           `id` but have `repo_id = NULL`.

        ### ID Types Explained

        - **`opendevdata_id`**: Original ID from Open Dev Data (`stg_opendevdata__repos.id`)
        - **`github_graphql_id`**: GitHub's GraphQL API node ID (from Open Dev Data)
        - **`repo_id`**: Unified repository identifier from OSSD or GitHub Archive
        - **`repo_id_source`**: Indicates which source provided the `repo_id` ('ossd', 'gharchive', or 'opendevdata')
        """
    )
    return


@app.cell(hide_code=True)
def _(mo, pyoso_db_conn):
    import pandas as pd
    
    def get_format_mapping(df, include_percentage=False):
        """Generate format mapping for table display"""
        fmt = {}
        for c in df.columns:
            if df[c].dtype in ['int64', 'float64']:
                if include_percentage and 'percentage' in c.lower():
                    fmt[c] = '{:.2f}'
                elif '_id' in c or c == 'id' or 'count' in c.lower():
                    fmt[c] = '{:.0f}'
                elif include_percentage:
                    fmt[c] = '{:.0f}'
        return fmt
    
    # Get coverage statistics
    coverage_query = """
    SELECT 
      repo_id_source,
      COUNT(*) AS repository_count,
      COUNT(repo_id) AS repos_with_repo_id,
      COUNT(*) - COUNT(repo_id) AS repos_without_repo_id,
      ROUND(100.0 * COUNT(repo_id) / COUNT(*), 2) AS match_percentage
    FROM oso.int_opendevdata__repositories_with_repo_id
    GROUP BY repo_id_source
    ORDER BY repository_count DESC
    """
    
    coverage_df = mo.sql(coverage_query, engine=pyoso_db_conn, output=False)
    return coverage_df, pd, get_format_mapping


@app.cell(hide_code=True)
def _(mo, coverage_df):
    mo.md(
        """
        ## Coverage Overview

        This shows how many repositories were matched via each source and the overall match rate.
        """
    )
    return


@app.cell(hide_code=True)
def _(mo, coverage_df, get_format_mapping):
    mo.ui.table(coverage_df, format_mapping=get_format_mapping(coverage_df, include_percentage=True), show_column_summaries=False, show_data_types=False)
    return


@app.cell(hide_code=True)
def _(mo, pyoso_db_conn):
    # Get sample data showing the different ID types
    sample_query = """
    SELECT 
      opendevdata_id,
      github_graphql_id,
      repo_id,
      repo_name,
      repo_id_source,
      star_count,
      fork_count
    FROM oso.int_opendevdata__repositories_with_repo_id
    WHERE repo_id_source IN ('ossd', 'gharchive', 'opendevdata')
    ORDER BY star_count DESC NULLS LAST
    LIMIT 20
    """
    
    sample_df = mo.sql(sample_query, engine=pyoso_db_conn, output=False)
    return sample_df,


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ## Sample Repositories by Match Type

        Examples showing how different repositories are matched across the three sources. 
        Notice how `repo_id` is populated from different sources based on the `repo_id_source` field.
        """
    )
    return


@app.cell(hide_code=True)
def _(mo, sample_df, get_format_mapping):
    mo.ui.table(sample_df, format_mapping=get_format_mapping(sample_df), show_column_summaries=False, show_data_types=False)
    return


@app.cell(hide_code=True)
def _(mo, pyoso_db_conn):
    # Statistics by source
    stats_query = """
    SELECT 
      repo_id_source,
      COUNT(*) AS total_repos,
      COUNT(DISTINCT repo_id) AS unique_repo_ids,
      AVG(star_count) AS avg_stars,
      AVG(fork_count) AS avg_forks,
      SUM(star_count) AS total_stars,
      SUM(fork_count) AS total_forks
    FROM oso.int_opendevdata__repositories_with_repo_id
    GROUP BY repo_id_source
    ORDER BY total_repos DESC
    """
    
    stats_df = mo.sql(stats_query, engine=pyoso_db_conn, output=False)
    return stats_df,


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ## Statistics by Match Source

        Aggregated statistics showing the characteristics of repositories matched via each source.
        """
    )
    return


@app.cell(hide_code=True)
def _(mo, stats_df, get_format_mapping):
    mo.ui.table(stats_df, format_mapping=get_format_mapping(stats_df, include_percentage=True), show_column_summaries=False, show_data_types=False)
    return


@app.cell(hide_code=True)
def _(mo, pyoso_db_conn):
    # Show repositories that matched via OSSD (primary match)
    ossd_match_query = """
    SELECT 
      r.opendevdata_id,
      r.repo_name,
      r.repo_id,
      r.star_count,
      r.fork_count,
      r.repo_created_at
    FROM oso.int_opendevdata__repositories_with_repo_id AS r
    WHERE r.repo_id_source = 'ossd'
    ORDER BY r.star_count DESC
    LIMIT 10
    """
    
    ossd_df = mo.sql(ossd_match_query, engine=pyoso_db_conn, output=False)
    return ossd_df,


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ## Top Repositories Matched via OSSD (Primary Match)

        These repositories were successfully matched using GitHub GraphQL ID, providing the most 
        reliable `repo_id` mapping.
        """
    )
    return


@app.cell(hide_code=True)
def _(mo, ossd_df, get_format_mapping):
    mo.ui.table(ossd_df, format_mapping=get_format_mapping(ossd_df), show_column_summaries=False, show_data_types=False)
    return


@app.cell(hide_code=True)
def _(mo, pyoso_db_conn):
    # Show repositories that matched via GitHub Archive (fallback)
    gharchive_match_query = """
    SELECT 
      r.opendevdata_id,
      r.repo_name,
      r.repo_id,
      r.star_count,
      r.fork_count,
      r.repo_created_at
    FROM oso.int_opendevdata__repositories_with_repo_id AS r
    WHERE r.repo_id_source = 'gharchive'
    ORDER BY r.star_count DESC
    LIMIT 10
    """
    
    gharchive_df = mo.sql(gharchive_match_query, engine=pyoso_db_conn, output=False)
    return gharchive_df,


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ## Top Repositories Matched via GitHub Archive (Fallback)

        These repositories didn't have a GitHub GraphQL ID match in OSSD, but were matched by 
        repository name to GitHub Archive data.
        """
    )
    return


@app.cell(hide_code=True)
def _(mo, gharchive_df, get_format_mapping):
    mo.ui.table(gharchive_df, format_mapping=get_format_mapping(gharchive_df), show_column_summaries=False, show_data_types=False)
    return


@app.cell(hide_code=True)
def _(mo, pyoso_db_conn):
    # Show unmatched repositories
    unmatched_query = """
    SELECT 
      opendevdata_id,
      repo_name,
      github_graphql_id,
      star_count,
      fork_count,
      repo_created_at
    FROM oso.int_opendevdata__repositories_with_repo_id
    WHERE repo_id_source = 'opendevdata' AND repo_id IS NULL
    ORDER BY star_count DESC
    LIMIT 10
    """
    
    unmatched_df = mo.sql(unmatched_query, engine=pyoso_db_conn, output=False)
    return unmatched_df,


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ## Top Unmatched Repositories

        These repositories couldn't be matched to either OSSD or GitHub Archive. They may be:
        - Very new repositories not yet in our systems
        - Repositories with name changes that don't match current names
        - Repositories that exist only in Open Dev Data
        """
    )
    return


@app.cell(hide_code=True)
def _(mo, unmatched_df, get_format_mapping):
    mo.ui.table(unmatched_df, format_mapping=get_format_mapping(unmatched_df), show_column_summaries=False, show_data_types=False)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ## Summary

        The Repositories model successfully unifies repository data from multiple sources:

        - **Primary matching** via GitHub GraphQL ID provides the most reliable `repo_id` mapping
        - **Fallback matching** via repository name captures additional repositories from GitHub Archive
        - **Coverage statistics** show the breadth of data integration across sources

        This unified `repo_id` enables consistent analysis across all OSO data products, regardless 
        of the original data source.
        """
    )
    return


if __name__ == "__main__":
    app.run()
