import marimo

__generated_with = "0.18.4"
app = marimo.App(width="full")


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        # Welcome to the Developer Data Portal

        The Developer Data Portal provides interactive access to OSO's comprehensive developer 
        and repository analytics. Explore data sources, models, metrics, and insights through 
        interactive notebooks powered by Marimo.

        ## What's Available

        ### Data Sources
        Explore raw data from multiple providers:
        - **OSS Directory**: Curated registry of open source projects and repositories
        - **Open Dev Data**: Developer activity metrics and ecosystem mappings from Electric Capital
        - **GitHub Archive**: Historical GitHub event data from gharchive.org

        ### Data Models
        Unified models that combine data across sources:
        - **Repositories**: Unified repository identifiers and metadata
        - **Developers**: Developer profiles and activity
        - **Ecosystems**: Ecosystem hierarchies and relationships
        - **Events**: GitHub events and activity
        - **Timeseries Metrics**: Time-based analytics and trends

        ### Insights
        Pre-built analyses and visualizations:
        - Developer Activity patterns
        - Developer Lifecycle metrics
        - Developer Retention analysis

        ## Getting Started

        Navigate to **Quick Start** in the sidebar for a guided introduction, or explore 
        any section to dive into the data.
        """
    )
    return


@app.cell(hide_code=True)
def _(mo, pyoso_db_conn):
    # Show overview of projects
    df = mo.sql("SELECT * FROM projects_v1 LIMIT 10", engine=pyoso_db_conn, output=False)
    return df,


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        ## Sample Projects

        Here's a preview of projects available in the OSO data lake:
        """
    )
    return


@app.cell(hide_code=True)
def _(mo, df):
    fmt = {c: '{:.0f}' for c in df.columns if df[c].dtype == 'int64' and ('_id' in c or c == 'id')}
    mo.ui.table(df, format_mapping=fmt, show_column_summaries=False, show_data_types=False)
    return


@app.cell
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


if __name__ == "__main__":
    app.run()
