import marimo

__generated_with = "0.18.4"
app = marimo.App(width="full")


@app.cell(hide_code=True)
def _(mo):
    mo.vstack([
        mo.md("""
    # Publications

    Research and analysis powered by DDP data.
    """),
        mo.callout(mo.md("This page is a placeholder. Links and descriptions may be incomplete or inaccurate."), kind="warn"),
    ])
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    ## Electric Capital Developer Reports

    Annual reports analyzing the state of open source crypto development, built on [Open Dev Data](https://opendevdata.org).

    - [**2024 Developer Report**](https://www.developerreport.com/developer-report?s=report-2024) — 902 million code commits across 1.7 million repositories
    - [**2023 Developer Report**](https://www.developerreport.com/developer-report?s=report-2023) — 485 million code commits across 818K repositories
    - [**2022 Developer Report**](https://www.developerreport.com/developer-report?s=report-2022) — 471K+ monthly code commits toward open source crypto projects
    - [**2021 Developer Report**](https://www.developerreport.com/developer-report?s=report-2021) — Nearly 500K code repositories and 160 million code commits
    - [**2020 Developer Report**](https://www.developerreport.com/developer-report?s=report-2020) — 276K+ code repositories and 89 million code commits
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    ## OSO Blog

    Selected posts from the [OSO blog](https://docs.oso.xyz/blog/) on data infrastructure, funding analysis, and ecosystem research.

    - [**Introducing Pyoso**](https://docs.oso.xyz/blog/pyoso) (Mar 2025) — A Python library for direct access to OSO's production datasets
    - [**Unpacking Optimism's Retro Funding Season 7**](https://docs.oso.xyz/blog/retro-funding-s7) (Apr 2025) — How OSO implemented evaluation algorithms for Optimism's latest funding round
    - [**Analyzing Retro Funding S7: Developer Tooling**](https://docs.oso.xyz/blog/retro-funding-s7-dev-tooling) (Jul 2025) — Which developer tools received funding and their measurable Superchain impact
    - [**Analyzing Retro Funding S7: Onchain Builders**](https://docs.oso.xyz/blog/retro-funding-s7-onchain-builders) (Jul 2025) — Onchain builder funding allocation and ecosystem impact across the Superchain
    - [**OSO's Architecture Evolution**](https://docs.oso.xyz/blog/architecture-evolution) (Apr 2025) — Technical infrastructure decisions and iterations throughout 2024
    - [**Opening up the Ballot Box (RF6)**](https://docs.oso.xyz/blog/rf6-ballot-box) (Dec 2024) — Ballot analysis showing visibility vs measurable long-term impact disparities
    - [**Looking Back at Octant's Funding in 2024**](https://docs.oso.xyz/blog/octant-2024) (Jan 2025) — Review of Octant's ~$5M in contributions to 60+ ecosystem projects
    """)
    return


@app.cell(hide_code=True)
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


if __name__ == "__main__":
    app.run()
