import marimo

__generated_with = "0.17.5"
app = marimo.App(width="full")


@app.cell
def title_markdown(mo):
    mo.md(r"""
    # One line solution title
    """)
    return


@app.cell
def analysis_settings(mo):
    # come up with a relevant set of UI controls

    item_select1 = mo.ui.dropdown(
        options=['Option 1', 'Option 2'],
        value='Option 1',
        label="Select an Option:"
    )
    item_select2 = mo.ui.dropdown(
        options=['Option 1', 'Option 2'],
        value='Option 1',
        label="Select Another Option:"
    )
    date_select = mo.ui.date(
        value="2025-01-01",
        label="Select a Date:"
    )
    switch_select = mo.ui.switch(
        value=True,
        label="Activate Switch",
    )
    mo.vstack([
        mo.md("### Analysis Settings:"),
        mo.hstack([item_select1, item_select2, date_select, switch_select], widths="equal", gap=2)
    ])
    return


@app.cell
def analysis_results(df, make_figure, mo):
    _df = df.copy()

    # apply filters from UI controls before making chart
    _fig = make_figure(dataframe=_df)

    # calculate stats from filtered and pre-filtered data
    stat1 = mo.stat(label="Stat1", bordered=True, value=1, caption="Out of X projects")
    stat2 = mo.stat(label="Stat2", bordered=True, value="50.5", caption="Based on this definition")
    stat3 = mo.stat(label="Stat3", bordered=True, value="33%", caption="+20% since last period")

    # generate the results dashboard
    mo.vstack([
        mo.md("### Analysis Results:"),
        mo.hstack([stat1, stat2, stat3], widths="equal", gap=1),
        mo.md("#### **Title for figure**"),
        mo.ui.plotly(_fig, config={'displayModeBar': False})
    ])
    return


@app.cell
def make_figure(px):
    # Create a stunning visual
    # OSO brand colors on white background with black text
    #253494
    #2C7FB8
    #41B6C4
    #99D8C9
    #253494
    #FFF2C2

    def make_figure(dataframe):
        fig = px.scatter(
            data_frame=dataframe,
            x='date',
            y='amount',
            color='project_name'
        )
        fig.update_layout(
            template="plotly_white", paper_bgcolor="white", plot_bgcolor="white",
            font=dict(size=12, color="#111"), margin=dict(l=0, r=0, t=0, b=0),
            title="", showlegend=False)
        fig.update_xaxes(title="", showgrid=False, visible=True, linecolor="#000", linewidth=1)
        fig.update_yaxes(title="", showgrid=True, visible=True, linecolor="#000", linewidth=1, zeroline=True, rangemode='tozero')
        return fig
    return (make_figure,)


@app.cell
def get_data(pd):
    # either inline or import dummy data from CSV / JSON
    _path = "marimo/web-assets/data/template-data.csv"
    df = pd.read_csv(_path)
    df['date'] = pd.to_datetime(df['date'])
    return (df,)


@app.cell
def import_libraries():
    import pandas as pd
    import plotly.express as px
    return px, pd


@app.cell
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return (mo,)


if __name__ == "__main__":
    app.run()
