import marimo

__generated_with = "0.18.4"
app = marimo.App(width="full")


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        """
        # Quick Start Guide

        Welcome to the Developer Data Portal! This guide will help you get started exploring 
        OSO's developer and repository data.

        ## Understanding the Portal Structure

        The portal is organized into three main sections:

        ### 1. Data Sources
        Raw data from external providers. Each source notebook shows:
        - **Table previews**: Interactive accordions with sample data
        - **SQL snippets**: Copy-able queries showing all available columns
        - **Row counts**: See the scale of each dataset

        Start here to understand what raw data is available.

        ### 2. Data Models
        Unified models that combine data across multiple sources. These notebooks explain:
        - **Data lineage**: How different sources are joined together
        - **ID mappings**: How different identifier systems work together
        - **Coverage analysis**: Breadth of data integration

        Use these to understand how disparate datasets are unified.

        ### 3. Insights
        Pre-built analyses and visualizations for common questions about developer activity, 
        lifecycle, and retention.

        ## How to Use This Portal

        1. **Explore Sources**: Start with the Data > Sources section to see what raw data 
           is available. Each table includes a SQL snippet you can copy and modify.

        2. **Understand Models**: Check out Data > Models to see how we combine data across 
           sources. The Repositories model is a great example of ID mapping and lineage.

        3. **Run Your Own Queries**: Use the SQL snippets as starting points. Copy them into 
           your own notebooks or modify them to answer your specific questions.

        4. **Review Insights**: Browse the Insights section for pre-built analyses that might 
           answer your questions or inspire new ones.

        ## Tips

        - **SQL Snippets**: All source notebooks include copy-able SQL queries. These are 
          formatted with one column per line for easy reading and modification.

        - **Table Formatting**: ID columns are automatically formatted without decimals for 
          better readability.

        - **Interactive Tables**: Click on column headers to sort, and use the search/filter 
          features in the table interface.

        ## Next Steps

        - Explore the **OSS Directory** source to see curated project data
        - Check out the **Repositories** model to understand how we unify repository identifiers
        - Browse **Insights** for ready-made analyses

        Happy exploring!
        """
    )
    return


@app.cell
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


if __name__ == "__main__":
    app.run()
